services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    shm_size: 128mb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=$PG_SUPERUSER_PASSWORD
    networks:
      - mk_network
    profiles:
      - dev
      - prod

  server:
    image: ghcr.io/bstempelj/memory-kana:0.3.0
    container_name: memory-kana
    restart: unless-stopped
    ports:
      - 127.0.0.1:1234:1234
    environment:
      - CSRF_AUTH_KEY=$CSRF_AUTH_KEY
      - HOST_ENV=prod
      - PGDATABASE=memorykana
      - PGHOST=postgres
      - PGPASSWORD=$PG_SUPERUSER_PASSWORD
      - PGSSLMODE=disable
      - PGUSER=postgres
    depends_on:
      - postgres
    networks:
      - mk_network
    profiles:
      - prod

networks:
  mk_network:
    driver: bridge

volumes:
  pg_data:
