---
services:
  postgres:
    image: postgres:16.3-alpine
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 3
    profiles:
      - dev
      - prod

  server:
    image: blazstempelj/memory-kana:0.0.1
    restart: unless-stopped
    ports:
      - 1234:1234
    environment:
      - HOST_ENV=prod
      - CSRF_AUTH_KEY=${CSRF_AUTH_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - prod

volumes:
  pg_data:
