---

- name: create ansible user named ansible
  hosts: all
  user: root
  become: true

  tasks:
    - name: create group ansible
      ansible.builtin.group:
        name: ansible
        state: present

    - name: create user ansible
      ansible.builtin.user:
        name: ansible
        group: ansible
        # todo: store password in ansible vault
        password: "{{ 'password' | password_hash('sha512') }}"
        shell: /bin/bash
        create_home: true
        state: present

    - name: add ansible to sudoers
      ansible.builtin.user:
        name: ansible
        groups: sudo
        append: true

    - name: add authorized key for the new user
      ansible.builtin.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '../ansible-sshkey.pub') }}"

    - name: update .ssh directory permissions
      ansible.builtin.file:
        path: /home/ansible/.ssh
        mode: '0700'

    - name: update authorized_keys file permissions
      ansible.builtin.file:
        path: /home/ansible/.ssh/authorized_keys
        mode: '0600'
