name: github-ci
on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          skip-cache: true
          install-mode: binary

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: go test
        run: go test ./...

  build:
    runs-on: ubuntu-24.04
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login into ghcr
        if: github.ref_type == 'tag'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: build ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref_type == 'tag' }}
          tags: |
            ghcr.io/${{ github.repository }}/memory-kana:${{ github.ref_name }}
